# Generated by Django 3.2 on 2022-05-23 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_course_coursesteachers_lesson'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='deleated',
            new_name='deleted',
        ),
        migrations.RenameField(
            model_name='coursesteachers',
            old_name='deleated',
            new_name='deleted',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='deleated',
            new_name='deleted',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='deleated',
            new_name='deleted',
        ),
    ]
